# Generated by Django 5.1.1 on 2024-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0011_update_defaults_and_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="id",
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="enumgroup",
            name="id",
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="enumvalue",
            name="id",
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="id",
            field=models.CharField(
                editable=False, max_length=40, primary_key=True, serialize=False
            ),
        ),
    ]
