# Generated by Django 5.1.2 on 2024-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0014_auto_20241120_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enumgroup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
