# Generated by Django 5.1.2 on 2024-11-20 11:03

from django.db import connection, migrations


def set_enumgroup_id_sequence(apps, schema_editor):
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('eav_enumgroup', 'id'), 100, false);"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0015_alter_enumgroup_id"),
    ]

    operations = [
        migrations.RunPython(set_enumgroup_id_sequence),
    ]
