# Generated by Django 5.1.2 on 2024-11-20 11:19

from django.db import connection, migrations, models


def set_attribute_id_sequence(apps, schema_editor):
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('eav_attribute', 'id'), 100, false);"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0016_auto_20241120_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_attribute_id_sequence),
    ]
