# Generated by Django 4.2.16 on 2024-11-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0017_auto_20241120_1519"),
    ]

    operations = []
