# Generated by Django 4.2.16 on 2024-11-26 04:12

from django.db import connection, migrations, models


def set_value_id_sequence(apps, schema_editor):
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('eav_value', 'id'), 100, false);"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("eav", "0018_alter_enumgroup_id_alter_value_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RunPython(set_value_id_sequence),
    ]
